services:
  todolist_app:
    container_name: tareas_app
    build: .
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://todolist_db:5432/GestorTareas
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - todolist_db
    volumes:
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvm spring-boot:run

  todolist_db:
    container_name: todolist_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GestorTareas

  todolist_test:
    container_name: todolist_test
    image: maven:3.8.4-openjdk-17-slim
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - todolist_db
    command: mvn test

